---
version: "2"
run:
  concurrency: 6
  build-tags:
    - integration
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
    # - cyclop
    # - depguard
    # - err113
    # - exhaustruct
    # - forcetypeassert
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gosec
    # - inamedparam
    # - interfacebloat
    # - ireturn
    # - lll
    # - mnd
    # - musttag
    # - nilerr
    # - nilnil
    # - nonamedreturns
    # - paralleltest
    # - testpackage
    # - thelper
    # - tparallel
    # - varnamelen
    # - wrapcheck
  settings:
    gocognit:
      min-complexity: 40
    gocritic:
      enabled-checks:
        - appendCombine
        - badLock
        - badRegexp
        - badSorting
        - badSyncOnceFunc
        - boolExprSimplify
        - builtinShadow
        - builtinShadowDecl
        - commentedOutCode
        - commentedOutImport
        - deferInLoop
        - deferUnlambda
        - docStub
        - dupImport
        - dynamicFmtString
        - emptyDecl
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - evalOrder
        - exposedSyncMutex
        - externalErrorReassign
        - filepathJoin
        - hexLiteral
        - httpNoBody
        - hugeParam
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - preferDecodeRune
        - preferFilepathJoin
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - ptrToRefParam
        - rangeAppendAll
        - rangeExprCopy
        - rangeValCopy
        - redundantSprint
        - regexpPattern
        - regexpSimplify
        - returnAfterHttpError
        - ruleguard
        - sliceClear
        - sloppyReassign
        - sortSlice
        - sprintfQuotedString
        - sqlQuery
        - stringConcatSimplify
        - stringXbytes
        - stringsCompare
        - syncMapLoadAndDelete
        - timeExprSimplify
        - todoCommentWithoutDetail
        - tooManyResultsChecker
        - truncateCmp
        - typeAssertChain
        - typeDefFirst
        - typeUnparen
        - uncheckedInlineErr
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - yodaStyleExpr
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
