---
name: e2e
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    if: github.repository == 'kubernetes-sigs/release-sdk'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup golang
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: Run local registry
        run: podman run -d -p 5000:5000 registry:2

      - name: Build test image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        id: test-image
        with:
          base-image: scratch
          image: test
          oci: true

      - name: Push test image to local registry
        id: push
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.test-image.outputs.image }}
          registry: localhost:5000
          tls-verify: false

      - name: Generate test file
        id: test-file
        run: |
          echo "release sign test" > ${{ runner.temp }}/test-file-${{ github.run_id }}

      - name: Run e2e tests
        run: go run mage.go E2ETest
        env:
          INPUT_PATH: ${{ runner.temp }}/test-file-${{ github.run_id }}
